version: 2.1

# the default pipeline parameters, which will be updated according to
# the results of the path-filtering orb
parameters:
  build-docs:
    type: boolean
    default: false
  build-infra:
    type: boolean
    default: false
  build-code:
    type: boolean
    default: false

workflows:
  build-docs:
    when: << pipeline.parameters.run-docs-workflow >>
    jobs:
      - say-hello-docs
      # other jobs here

  build-infra:
    when: << pipeline.parameters.run-infra-workflow >>
    jobs:
      - say-hello-infra
      # other jobs here

  build-code:
    when: << pipeline.parameters.run-code-workflow >>
    jobs:
      - say-hello-code
      # other jobs here
    

jobs:
  say-hello-docs:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Mkdocs here"

  say-hello-infra:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Terraform some stuff"

  say-hello-code:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
